repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: trailing-whitespace
        - id: detect-aws-credentials
        - id: check-added-large-files
        - id: check-yaml
        - id: detect-private-key

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.81.0
      hooks:
      - id: terraform_fmt
        files: ^infrastructure/
      - id: terraform_validate
        files: ^infrastructure/

    - repo: https://github.com/terraform-docs/terraform-docs
      rev: "v0.16.0"
      hooks:
      - id: terraform-docs-go
        args: ["--config", ".terraform-docs.yml", "./infrastructure/tf/"]
        files: ^infrastructure/